### ISSUE TITLE
Retirement of Dependencies API breaks clients that cannot access rubygems

### ISSUE THREAD

**Issue by tedgarb** [rubygems/gemstash#336] opened 2023-04-11 15:45 UTC
Discovered this today, believed to be fallout from https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html . When I try to install a gem using my mirror (e.g. net-ldap), the following is the verbose logs of installing on a client that does not have access to rubygems.org:

```gem install --no-document --source http://my-mirror.com/rubygems/ net-ldap -V
HEAD http://my-mirror.com/rubygems/api/v1/dependencies
200 OK
GET http://my-mirror.com/rubygems/api/v1/dependencies?gems=net-ldap
404 Not Found
GET http://my-mirror.com/rubygems/prerelease_specs.4.8.gz
302 Found
GET http://my-mirror.com/rubygems/specs.4.8.gz
302 Found
ERROR:  Could not find a valid gem 'net-ldap' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ENETUNREACH: Failed to open TCP connection to rubygems.org:443 (Network is unreachable - connect(2) for "rubygems.org" port 443) (https://rubygems.org/specs.4.8.gz)
          Unable to download data from http://my-mirror.com/rubygems/ - Errno::ENETUNREACH: Failed to open TCP connection to rubygems.org:443 (Network is unreachable - connect(2) for "rubygems.org" port 443) (http://my-mirror.com/rubygems/specs.4.8.gz)
GET http://my-mirror.com/rubygems/latest_specs.4.8.gz
302 Found
GET http://my-mirror.com/rubygems/prerelease_specs.4.8.gz
302 Found
```

with this in the gemstash server log:
```[2023-04-11 11:28:38 -0400] - INFO - Fetching dependencies: net-ldap
[2023-04-11 11:28:38 -0400] - ERROR - 2023-04-11 11:28:38 - Gemstash::WebError - The dependency API is going away. See https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html for more information:
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/http_client.rb:62:in `get'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/dependencies.rb:80:in `fetch_from_web'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/dependencies.rb:43:in `fetch'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/dependencies.rb:24:in `fetch'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/gem_source/dependency_caching.rb:15:in `serve_dependencies'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/web.rb:43:in `block in <class:Web>'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `call'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `block in compile!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1049:in `route_eval'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1078:in `block in process_route'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `catch'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `process_route'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1028:in `block in route!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `each'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `route!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1147:in `block in dispatch!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1142:in `dispatch!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `block in call!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `call!'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:945:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/base.rb:50:in `call'
	/usr/local/share/gems/gems/rack-protection-2.2.4/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/share/gems/gems/rack-2.2.6.4/lib/rack/null_logger.rb:11:in `call'
	/usr/local/share/gems/gems/rack-2.2.6.4/lib/rack/head.rb:12:in `call'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:218:in `call'
	/usr/local/share/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:2004:in `call'
	/usr/local/share/gems/gems/server_health_check-rack-0.1.0/lib/server_health_check_rack/middleware.rb:12:in `call'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/gem_source/rack_middleware.rb:21:in `call'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/env.rb:38:in `call'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/commonlogger.rb:40:in `call'
	/usr/local/share/gems/gems/gemstash-2.2.2/lib/gemstash/logging.rb:58:in `call'
	/usr/local/share/gems/gems/rack-2.2.6.4/lib/rack/deflater.rb:44:in `call'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/configuration.rb:228:in `call'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/server.rb:727:in `handle_request'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/server.rb:476:in `process_client'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/server.rb:332:in `block in run'
	/usr/local/share/gems/gems/puma-4.3.12/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
[2023-04-11 11:28:38 -0400] - INFO - 128.2.140.85 - - [11/Apr/2023:11:28:38 -0400] "GET /api/v1/dependencies?gems=net-ldap HTTP/1.1" 500 151460 0.0734
```

For comparision, a client that can reach rubygems.org shows this:
```gem install --no-document --clear-sources --source http://my-mirror.com/rubygems/ net-ldap -V
HEAD http://my-mirror.com/rubygems/api/v1/dependencies
200 OK
GET http://my-mirror.com/rubygems/api/v1/dependencies?gems=net-ldap
500 Internal Server Error
GET http://my-mirror.com/rubygems/prerelease_specs.4.8.gz
302 Found
GET https://rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET http://my-mirror.com/rubygems/specs.4.8.gz
302 Found
GET https://rubygems.org/specs.4.8.gz
304 Not Modified
```

I believe the issue here is that gemstash is simply pawning off the spec download by serving a 302, rather than intermediating the download. When the dependency API was up, and this was intermediated, the problem was masked, but now that the dependency API is gone, this renders gemstash unusable for clients that cannot access rubygems directly to get specs.

**Comment by marvinthepa** [comment] 2023-05-30 15:51
Maybe the quickfix as described in https://github.com/geminabox/geminabox/issues/536#issuecomment-1568675579 will also work for gemstash.

It is a workaround at best, as it will force clients to use a full index download.

**Comment by tedgarb** [comment] 2023-06-14 14:01
Could I get an update on this?

**Comment by indirect** [comment] 2023-06-14 20:00
it's still broken! pull requests welcomed.

**Comment by LeaRhh** [comment] 2024-02-06 13:02
Hi ! 

I see the issue is still open, and was wondering if previous merged request should have fixed it ?

I met the same yesterday while starting my gemstash journey (and having client with no internet access). 

Here are my logs just in case
On my gemstash server (gemstash 2.7.1) :
```
[2024-02-05 16:24:14 +0100] - INFO - * Listening on http://0.0.0.0:9292
[2024-02-05 16:24:14 +0100] - INFO - Use Ctrl-C to stop
[2024-02-05 16:24:21 +0100] - INFO - Rewriting '/private/versions' to '/versions'
[2024-02-05 16:24:21 +0100] - INFO - Rewriting '/private/api/v1/dependencies' to '/api/v1/dependencies'
[2024-02-05 16:24:21 +0100] - INFO - Rewriting '/private/api/v1/dependencies?gems=my-priv-gem' to '/api/v1/dependencies?gems=my-priv-gem'
[2024-02-05 16:24:21 +0100] - INFO - Querying dependencies: my-priv-gem
[2024-02-05 16:24:21 +0100] - INFO - Rewriting '/private/quick/Marshal.4.8/my-priv-gem-0.4.4.gemspec.rz' to '/quick/Marshal.4.8/my-priv-gem-0.4.4.gemspec.rz'
[2024-02-05 16:24:51 +0100] - INFO - Fetching dependencies: my-dependency-1,my-dependency-2
[2024-02-05 16:24:52 +0100] - ERROR - 2024-02-05 16:24:52 - Gemstash::WebError - The dependency API is going away. See https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html for more information:
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/http_client.rb:62:in `get'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/dependencies.rb:80:in `fetch_from_web'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/dependencies.rb:43:in `fetch'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/dependencies.rb:24:in `fetch'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/gem_source/dependency_caching.rb:15:in `serve_dependencies'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/web.rb:43:in `block in <class:Web>'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1775:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1775:in `block in compile!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1065:in `block (3 levels) in route!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1083:in `route_eval'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1065:in `block (2 levels) in route!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1114:in `block in process_route'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1112:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1112:in `process_route'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1063:in `block in route!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1060:in `each'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1060:in `route!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1184:in `block in dispatch!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `invoke'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1179:in `dispatch!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:995:in `block in call!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `catch'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:1155:in `invoke'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:995:in `call!'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:984:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/xss_header.rb:20:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/path_traversal.rb:18:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/json_csrf.rb:28:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/base.rb:53:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/base.rb:53:in `call'
	/var/lib/gems/2.7.0/gems/rack-protection-3.2.0/lib/rack/protection/frame_options.rb:33:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.8/lib/rack/null_logger.rb:11:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/show_exceptions.rb:23:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:219:in `call'
	/var/lib/gems/2.7.0/gems/sinatra-3.2.0/lib/sinatra/base.rb:2086:in `call'
	/var/lib/gems/2.7.0/gems/server_health_check-rack-0.1.0/lib/server_health_check_rack/middleware.rb:12:in `call'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/gem_source/rack_middleware.rb:21:in `call'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/env.rb:38:in `call'
	/var/lib/gems/2.7.0/gems/gemstash-2.7.1/lib/gemstash/logging.rb:64:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.8/lib/rack/deflater.rb:44:in `call'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
	/var/lib/gems/2.7.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

And client side logs (shortened) : 
```
Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching http://x-oauth-basic@mygemeserver.domain:9292/api/v1/dependencies?gems=[...] (Net::ReadTimeout)
```

**Closed** 2024-02-14 19:23 UTC
